# Generated by Django 5.0.4 on 2026-03-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_property_image_property_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
